/**
 * 主页内容都集中在这里。
 * 把城市、邮箱和简介替换成你的真实信息即可。
 * 上传作品的方法见项目根目录 ARTWORKS.md。
 */
export const portfolio = {
  name: "YoaUuki",
  year: "2026",
  range: "2024—2026",
  eyebrow: "ILLUSTRATION ARTIST · BASED IN CHINA",
  headline: "YoaUuki’s Illustration Collection",
  intro:
    "以植物、梦境与城市碎片为线索，记录那些介于真实与虚构之间的瞬间。",
  aboutTitle: "我們的人生只是一个无可挽回的消逝过程的印象和反映",
  aboutTitleEn: "Our lives reflect an irreversible process of vanishing.",
  about: [
    "YoaUuki 的創作長期聚焦於復古與懷舊的視覺語境，將記憶、時間與身體感知作為持續探索的核心命題。她相信，人生並非由宏大的事件構成，而是由無數細微、易逝的瞬間累積而成；那些難以言說的情緒、日常生活中稍縱即逝的感受，以及被時間反覆沖淡的記憶，共同構成了生命存在的印象與反映。",
    "她的插畫經常關注那些容易被忽略的微小情緒：沉默、遲疑、依戀、失落、平靜，或某種無法準確命名的感受。植物則成為她創作中重要的象徵語言，既是生命循環的隱喻，也是身體感知的延伸。葉片、根系、花朵與枝蔓被抽象化為情緒與身體的載體，使內在經驗得以轉化為可視的圖像。",
    "YoaUuki 同時使用數位媒介與紙本媒介進行創作，並依據不同主題選擇相應的技術語言。她的作品可能呈現截然不同的視覺風格：有時保留紙張、顏料與筆觸帶來的溫度，有時則透過數位繪畫建立更自由的敘事與色彩結構。然而，媒介與形式的變化並未改變她始終如一的創作核心——以圖像保存那些正在流逝、卻仍然留存在感知中的情緒與記憶。",
    "對 YoaUuki 而言，創作並非試圖對抗時間，而是在不可逆的消逝之中，為生命留下短暫卻真實的印記。每一幅作品都是一段記憶的殘響、一種情緒的留存，也是對「我們的人生只是一个无可挽回的消逝过程的印象和反映」這一命題持續而溫柔的回應。",
  ],
  aboutEn: [
    "YoaUuki’s practice has long been rooted in the visual language of the vintage and the nostalgic, with memory, time and embodied perception forming the central concerns of her ongoing exploration. She believes that life is not composed of grand events, but accumulated through countless subtle and fleeting moments. Emotions that resist language, sensations that vanish in the course of everyday life, and memories repeatedly softened by time together form the impressions and reflections of our existence.",
    "Her illustrations often attend to small emotions that are easily overlooked: silence, hesitation, attachment, loss, calm, or a feeling that cannot be precisely named. Plants serve as an important symbolic language in her work—both metaphors for the cycles of life and extensions of bodily perception. Leaves, roots, flowers and vines are abstracted into vessels for emotion and the body, allowing inner experience to take visible form.",
    "YoaUuki works across both digital and paper-based media, choosing a technical language in response to each subject. Her works may take on distinctly different visual styles: at times retaining the warmth of paper, pigment and the artist’s hand; at others using digital painting to construct freer structures of narrative and colour. Yet these shifts in medium and form never alter the core of her practice—to preserve in images the emotions and memories that are passing away while remaining present in perception.",
    "For YoaUuki, making art is not an attempt to resist time. It is a way of leaving a brief yet truthful trace of life within an irreversible process of disappearance. Each work is the afterimage of a memory, the preservation of an emotion, and a continuing, gentle response to the proposition that “our lives are merely impressions and reflections of an irreversible process of vanishing.”",
  ],
  facts: [
    { label: "BASED IN", value: "CHINA" },
    { label: "WORKING WITH", value: "EDITORIAL · BOOKS · BRAND" },
    { label: "AVAILABLE FOR", value: "COMMISSIONS · COLLABORATIONS" },
  ],
  contactTitle: "让我们一起种下一个新故事。",
  contactText:
    "欢迎联系插画委托、出版合作、品牌项目与展览邀请。请把项目时间与简单需求写在邮件里。",
  email: "aokiyuuki@163.com",
} as const;

export type PortfolioWork = {
  slug: string;
  title: string;
  titleZh?: string;
  year: string;
  medium: string;
  alt: string;
  image?: string;
  artClass: "night" | "geometry" | "rain" | "afternoon";
  featured?: boolean;
};

/**
 * image 留空时显示带 PLACEHOLDER 标记的示例画面。
 * 上传真实作品后填写类似：image: "/works/my-artwork.jpg"
 */
export const works: PortfolioWork[] = [
  {
    slug: "digital-painting-01",
    title: "Through my blood",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色背景中，双手、白色百合与绿色枝叶交织",
    image: "/works/digital-painting-01.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "digital-painting-02",
    title: "Digital Painting 02",
    titleZh: "数字绘画 02",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "红色背景中，被绿色藤蔓缠绕的白色人物躯干",
    image: "/works/digital-painting-02.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "digital-painting-03",
    title: "Digital Painting 03",
    titleZh: "数字绘画 03",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "红色背景中，两个人物侧脸由绿色植物线条连接",
    image: "/works/digital-painting-03.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "digital-painting-04",
    title: "Digital Painting 04",
    titleZh: "数字绘画 04",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色背景中，双臂、双手、百合与绿色叶片向下延伸",
    image: "/works/digital-painting-04.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "digital-painting-05",
    title: "Digital Painting 05",
    titleZh: "数字绘画 05",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色背景中，交叠的手足与成簇白色百合",
    image: "/works/digital-painting-05.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "digital-painting-06",
    title: "Digital Painting 06",
    titleZh: "数字绘画 06",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝紫色背景中，人物拥抱花束，深绿色叶片环绕身体",
    image: "/works/digital-painting-06.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "digital-painting-07",
    title: "Digital Painting 07",
    titleZh: "数字绘画 07",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色背景中，蜷坐的人物肩头盛开白色百合",
    image: "/works/digital-painting-07.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "digital-painting-08",
    title: "Digital Painting 08",
    titleZh: "数字绘画 08",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色渐变背景中，一只手托起白色百合",
    image: "/works/digital-painting-08.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "digital-painting-09",
    title: "Digital Painting 09",
    titleZh: "数字绘画 09",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色渐变背景中，白色裙装、双腿、百合与紫色缎带",
    image: "/works/digital-painting-09.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "digital-painting-10",
    title: "Digital Painting 10",
    titleZh: "数字绘画 10",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "蓝色背景中，人物侧脸靠近盛开的白色百合",
    image: "/works/digital-painting-10.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const throughMyBloodProject = {
  slug: "through-my-blood",
  title: "Through my blood",
  year: "2026",
  medium: "Digital",
  description:
    "A series of ten digital paintings in which bodies, lilies and vine-like forms move across saturated fields of blue and red. Viewed as a sequence, the images connect touch, tension and transformation through a shared visual language.",
  works,
} as const;

export const addictedRedWorks: PortfolioWork[] = [
  {
    slug: "addicted-red-01",
    title: "Addicted red 01",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Four mirrored figures in red dresses framed by green looping stems",
    image: "/works/addicted-red-01.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "addicted-red-02",
    title: "Addicted red 02",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "A braided figure in a red dress standing in a pastel dream landscape",
    image: "/works/addicted-red-02.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "addicted-red-03",
    title: "Addicted red 03",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "A figure in red seated above a glossy red sphere between giant eyes",
    image: "/works/addicted-red-03.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "addicted-red-04",
    title: "Addicted red 04",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Three intertwined figures in red dresses against a deep red field",
    image: "/works/addicted-red-04.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "addicted-red-05",
    title: "Addicted red 05",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Figures in white dresses gather around black horses on a blue field",
    image: "/works/addicted-red-05.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "addicted-red-06",
    title: "Addicted red 06",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Two figures in red dresses moving beneath looping green stems",
    image: "/works/addicted-red-06.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "addicted-red-07",
    title: "Addicted red 07",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "A mirrored red-dressed figure surrounded by silver sculptural forms",
    image: "/works/addicted-red-07.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "addicted-red-08",
    title: "Addicted red 08",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Three red-dressed figures arranged inside a theatrical pink interior",
    image: "/works/addicted-red-08.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "addicted-red-09",
    title: "Addicted red 09",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Two figures in luminous red dresses standing beneath falling ribbons",
    image: "/works/addicted-red-09.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "addicted-red-10",
    title: "Addicted red 10",
    year: "2026",
    medium: "DIGITAL PAINTING",
    alt: "Two red skirts and stepping legs towering above a miniature night town",
    image: "/works/addicted-red-10.jpg",
    artClass: "rain",
    featured: true,
  },
];

export const addictedRedProject = {
  slug: "addicted-red",
  title: "Addicted red",
  year: "2026",
  medium: "Digital painting",
  description:
    "A series of ten digital paintings shaped by red dresses, repeated bodies, mirrored gestures and theatrical spaces. Across the sequence, saturated colour and looping forms turn repetition into a visual rhythm of desire, performance and entanglement.",
  works: addictedRedWorks,
} as const;

export const transientSpaceWorks: PortfolioWork[] = [
  {
    slug: "transient-space-01",
    title: "Transient space 01",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A green and blue architectural space filled with looping botanical lines",
    image: "/works/transient-space-01.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-02",
    title: "Transient space 02",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "White flowers and long green stems emerging through layered geometric forms",
    image: "/works/transient-space-02.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-03",
    title: "Transient space 03",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A dark suspended rectangular volume surrounded by vertical blue-green lines",
    image: "/works/transient-space-03.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "transient-space-04",
    title: "Transient space 04",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A luminous green room containing hills, flowers and looping stems",
    image: "/works/transient-space-04.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-05",
    title: "Transient space 05",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Eight green geometric boxes connected by winding architectural lines",
    image: "/works/transient-space-05.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-06",
    title: "Transient space 06",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "An expansive grid of green folded spaces threaded with looping lines",
    image: "/works/transient-space-06.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-07",
    title: "Transient space 07",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Stacked green structures and winding stems beneath a red circular sky",
    image: "/works/transient-space-07.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-08",
    title: "Transient space 08",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A deep green angular interior crossed by long horizontal plant-like lines",
    image: "/works/transient-space-08.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "transient-space-09",
    title: "Transient space 09",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Two transparent geometric vessels holding layered organic green forms",
    image: "/works/transient-space-09.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-10",
    title: "Transient space 10",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A yellow and green room framing a red basin and three white flowers",
    image: "/works/transient-space-10.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-11",
    title: "Transient space 11",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "White flowers and long green stems emerging through layered geometric forms",
    image: "/works/transient-space-11.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-12",
    title: "Transient space 12",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A reclining abstract figure formed from blue, green and violet washes",
    image: "/works/transient-space-12.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-13",
    title: "Transient space 13",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A luminous green landscape surrounding a row of folded white screens",
    image: "/works/transient-space-13.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-14",
    title: "Transient space 14",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Layered translucent arches crossed by a dark green looping line",
    image: "/works/transient-space-14.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-15",
    title: "Transient space 15",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Translucent architectural planes, botanical fragments and winding green paths",
    image: "/works/transient-space-15.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-16",
    title: "Transient space 16",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A yellow-green interior crossed by a dark line forming an infinity loop",
    image: "/works/transient-space-16.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-17",
    title: "Transient space 17",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Red, orange and green translucent shapes surrounding a tiled square and steps",
    image: "/works/transient-space-17.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-18",
    title: "Transient space 18",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A layered green interior with a white central frame and winding line",
    image: "/works/transient-space-18.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-19",
    title: "Transient space 19",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A red arched interior filled with purple mountains and glowing windows",
    image: "/works/transient-space-19.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "transient-space-20",
    title: "Transient space 20",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Six pairs of red shoes stepping across green stems inside a pink room",
    image: "/works/transient-space-20.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-21",
    title: "Transient space 21",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A luminous green forest-like space crossed by a pale branching form and a pink path",
    image: "/works/transient-space-21.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-22",
    title: "Transient space 22",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A layered blue and green architectural interior threaded with dark looping lines",
    image: "/works/transient-space-22.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-23",
    title: "Transient space 23",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A pair of red shoes rising from a dense nest of green lines inside a translucent room",
    image: "/works/transient-space-23.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-24",
    title: "Transient space 24",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A pale architectural interior containing a green tree, a bending figure and a winding dark form",
    image: "/works/transient-space-24.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "transient-space-25",
    title: "Transient space 25",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A green moonlit landscape enclosed by rounded red forms and a looping dark line",
    image: "/works/transient-space-25.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "transient-space-26",
    title: "Transient space 26",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A turquoise landscape of hills, clouds and repeated arches framed by soft pink contours",
    image: "/works/transient-space-26.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "transient-space-27",
    title: "Transient space 27",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A translucent green box covered by a dense nest of looping stems and white petals",
    image: "/works/transient-space-27.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "transient-space-28",
    title: "Transient space 28",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Repeated white legs in red shoes entangled by dark green loops over violet washes",
    image: "/works/transient-space-28.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "transient-space-29",
    title: "Transient space 29",
    year: "2024-2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Red shoes stepping across a green modular structure joined by a winding dark line",
    image: "/works/transient-space-29.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const transientSpaceProject = {
  slug: "transient-space",
  title: "Transient space",
  year: "2024-2025",
  medium: "Watercolor on paper",
  description:
    "A series of twenty-nine watercolours on paper exploring temporary architectures, looping botanical lines and shifting geometric enclosures. Green, blue and luminous yellow spaces hover between interior, landscape and remembered place.",
  works: transientSpaceWorks,
} as const;

export const stemWorks: PortfolioWork[] = [
  {
    slug: "stem-01",
    title: "stem 01",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Layered blue and green botanical spaces crossed by a large leaf and white flowers",
    image: "/works/stem-01.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "stem-02",
    title: "stem 02",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A blue-green interior with arching stems, white flowers and translucent geometric rooms",
    image: "/works/stem-02.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "stem-03",
    title: "stem 03",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A luminous white organic form suspended in a green and pink landscape of looping lines",
    image: "/works/stem-03.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "stem-04",
    title: "stem 04",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A framed night landscape surrounded by green foliage and rows of walking red shoes",
    image: "/works/stem-04.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "stem-05",
    title: "stem 05",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A solitary figure inside a coral room floating in a deep blue dream landscape",
    image: "/works/stem-05.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "stem-06",
    title: "stem 06",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "Soft violet flowers and branching white lines glowing against a deep green-blue square",
    image: "/works/stem-06.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "stem-07",
    title: "stem 07",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A translucent figure and tiled panels hovering above a pale architectural garden",
    image: "/works/stem-07.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "stem-08",
    title: "stem 08",
    year: "2025",
    medium: "WATERCOLOR ON PAPER",
    alt: "A pink and green interior with a tree, windows, a chair and bright star-shaped details",
    image: "/works/stem-08.jpg",
    artClass: "night",
    featured: true,
  },
];

export const stemProject = {
  slug: "stem",
  title: "stem",
  year: "2025",
  medium: "Watercolor on paper",
  description:
    "A series of eight watercolours on paper in which botanical stems, imagined rooms and translucent landscapes overlap. Layered washes of blue, green and pink turn enclosed spaces into shifting gardens of memory and perception.",
  works: stemWorks,
} as const;

export const moonInTheWaterWorks: PortfolioWork[] = [
  {
    slug: "moon-in-the-water-01",
    title: "Moon in the water 01",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A woman leans toward a reflected face held in a dish beneath a dense arrangement of flowers",
    image: "/works/moon-in-the-water-01.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "moon-in-the-water-02",
    title: "Moon in the water 02",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A woman in a flowing white dress floats over blue floral shadows with a hand covering her mouth",
    image: "/works/moon-in-the-water-02.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "moon-in-the-water-03",
    title: "Moon in the water 03",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A braided woman reaches toward a large open book spilling flowers above a crescent moon",
    image: "/works/moon-in-the-water-03.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "moon-in-the-water-04",
    title: "Moon in the water 04",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A ceremonial scene with a robed reader, women in white and lilies against a deep red interior",
    image: "/works/moon-in-the-water-04.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "moon-in-the-water-05",
    title: "Moon in the water 05",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "Two faceless figures embrace before a pale rectangular panel in a saturated red space",
    image: "/works/moon-in-the-water-05.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "moon-in-the-water-06",
    title: "Moon in the water 06",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A seated woman and two white swans overlap roses and green geometric frames",
    image: "/works/moon-in-the-water-06.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "moon-in-the-water-07",
    title: "Moon in the water 07",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A rabbit-masked figure in a blue skirt stands before branching forms and a second body",
    image: "/works/moon-in-the-water-07.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "moon-in-the-water-08",
    title: "Moon in the water 08",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A nude figure floats in a circular garden of green leaves and flowers on a crimson field",
    image: "/works/moon-in-the-water-08.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "moon-in-the-water-09",
    title: "Moon in the water 09",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A figure drapes over a geometric swing frame beside an arcade-like machine and white tulips",
    image: "/works/moon-in-the-water-09.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "moon-in-the-water-10",
    title: "Moon in the water 10",
    year: "2023",
    medium: "DIGITAL PAINTING",
    alt: "A white-haired figure in pink floats among tiled windows, plants and playful pastel objects",
    image: "/works/moon-in-the-water-10.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const moonInTheWaterProject = {
  slug: "moon-in-the-water",
  title: "Moon in the water",
  year: "2023",
  medium: "Digital painting",
  description:
    "A series of ten digital paintings that stage intimacy, ritual and transformation within saturated dream spaces. Reflections, books, flowers, animals and suspended bodies move between tenderness and unease, as if emerging from the surface of remembered water.",
  works: moonInTheWaterWorks,
} as const;

export const untitledPencilWorks: PortfolioWork[] = [
  {
    slug: "untitled-pencil-01",
    title: "untitled 01",
    year: "2023",
    medium: "PENCIL ON PAPER",
    alt: "A pencil portrait of a figure holding their hands together among large lilies",
    image: "/works/untitled-pencil-01.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "untitled-pencil-02",
    title: "untitled 02",
    year: "2023",
    medium: "PENCIL ON PAPER",
    alt: "A pair of legs and dark shoes emerging from a dense bed of tulips",
    image: "/works/untitled-pencil-02.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "untitled-pencil-03",
    title: "untitled 03",
    year: "2023",
    medium: "PENCIL ON PAPER",
    alt: "A braided figure seen from behind inside a transparent geometric enclosure filled with leaves",
    image: "/works/untitled-pencil-03.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "untitled-pencil-04",
    title: "untitled 04",
    year: "2023",
    medium: "PENCIL ON PAPER",
    alt: "A suspended ruffled skirt rising above a dense arrangement of lilies",
    image: "/works/untitled-pencil-04.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "untitled-pencil-05",
    title: "untitled 05",
    year: "2023",
    medium: "PENCIL ON PAPER",
    alt: "Three pairs of bent legs arranged among leaves inside a geometric box",
    image: "/works/untitled-pencil-05.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const untitledPencilProject = {
  slug: "untitled-pencil",
  title: "untitled",
  year: "2023",
  medium: "Pencil on paper",
  description:
    "A series of five pencil drawings on paper in which figures, flowers and enclosed spaces are woven through delicate graphite lines. Bodies appear, disappear and return as fragments within dense botanical arrangements, holding a quiet tension between intimacy and distance.",
  works: untitledPencilWorks,
} as const;

export const amusingOurselvesToDeathWorks: PortfolioWork[] = [
  {
    slug: "amusing-ourselves-to-death-01",
    title: "amusing ourselves to death 01",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A standing figure holding a black tablet, their face obscured by cascading blue flowers",
    image: "/works/amusing-ourselves-to-death-01.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-02",
    title: "amusing ourselves to death 02",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A curled figure in a pale dress resting among a school of fish",
    image: "/works/amusing-ourselves-to-death-02.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-03",
    title: "amusing ourselves to death 03",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A contemplative bare figure surrounded by purple morning glory flowers",
    image: "/works/amusing-ourselves-to-death-03.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-04",
    title: "amusing ourselves to death 04",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Pale mannequin-like figures intertwined within a translucent green haze",
    image: "/works/amusing-ourselves-to-death-04.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-05",
    title: "amusing ourselves to death 05",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A long-haired figure in a purple dress enclosed inside a glass botanical case",
    image: "/works/amusing-ourselves-to-death-05.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-06",
    title: "amusing ourselves to death 06",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A stylized profile blowing bubbles toward a cluster of orange-red circles",
    image: "/works/amusing-ourselves-to-death-06.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-07",
    title: "amusing ourselves to death 07",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A black cat carrying a red ball through luminous green grass",
    image: "/works/amusing-ourselves-to-death-07.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-08",
    title: "amusing ourselves to death 08",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A pale figure with a circular hollow head standing in a dense green plant field",
    image: "/works/amusing-ourselves-to-death-08.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-09",
    title: "amusing ourselves to death 09",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Two stylized profiles exchanging an image and a green leaf-like breath",
    image: "/works/amusing-ourselves-to-death-09.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-10",
    title: "amusing ourselves to death 10",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A small figure playing a flute in a luminous forest beside a parked bus",
    image: "/works/amusing-ourselves-to-death-10.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-11",
    title: "amusing ourselves to death 11",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A child draped playfully over a large red ball on a pale green field",
    image: "/works/amusing-ourselves-to-death-11.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-12",
    title: "amusing ourselves to death 12",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A blue-haired schoolgirl standing with two flamingos on colorful puzzle pieces",
    image: "/works/amusing-ourselves-to-death-12.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-13",
    title: "amusing ourselves to death 13",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A suited figure arches backward as their head dissolves into flowing green leaves",
    image: "/works/amusing-ourselves-to-death-13.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-14",
    title: "amusing ourselves to death 14",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A figure in white breathes into a dense current of blue and green leaves",
    image: "/works/amusing-ourselves-to-death-14.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-15",
    title: "amusing ourselves to death 15",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Leaping deer cross an arched garden around a seated bald figure",
    image: "/works/amusing-ourselves-to-death-15.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-16",
    title: "amusing ourselves to death 16",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A pianist seen from behind facing open sheet music amid glowing pink flowers",
    image: "/works/amusing-ourselves-to-death-16.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-17",
    title: "amusing ourselves to death 17",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A child watches a vast black whale swimming above a field of bright clouds",
    image: "/works/amusing-ourselves-to-death-17.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-18",
    title: "amusing ourselves to death 18",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A frontal portrait held within an ornate green frame with hands circling the eyes",
    image: "/works/amusing-ourselves-to-death-18.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "amusing-ourselves-to-death-19",
    title: "amusing ourselves to death 19",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A dark-haired figure holding a bowl of white calla lilies within layered blue arches",
    image: "/works/amusing-ourselves-to-death-19.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const amusingOurselvesToDeathProject = {
  slug: "amusing-ourselves-to-death",
  title: "amusing ourselves to death",
  year: "2021",
  medium: "Digital painting",
  description:
    "A series of nineteen digital paintings that place bodies, flowers, animals and constructed enclosures within dreamlike scenes of saturation and unease. Across the sequence, beauty and distraction become intertwined, reflecting on spectacle, consumption and the fragile attention of contemporary life.",
  works: amusingOurselvesToDeathWorks,
} as const;

export const kinderszenenWorks: PortfolioWork[] = [
  {
    slug: "kinderszenen-01",
    title: "Kinderszenen 01",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Two figures in pale clothing step through a dark doorway surrounded by giant green leaves",
    image: "/works/kinderszenen-01.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-02",
    title: "Kinderszenen 02",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A dark-haired musician holds a golden trombone beneath streams of liquid light",
    image: "/works/kinderszenen-02.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "kinderszenen-03",
    title: "Kinderszenen 03",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A shadowed figure stands alone in a sunlit greenhouse corridor filled with plants",
    image: "/works/kinderszenen-03.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "kinderszenen-04",
    title: "Kinderszenen 04",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A painter works at an easel in a luminous botanical courtyard with arches and stairs",
    image: "/works/kinderszenen-04.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "kinderszenen-05",
    title: "Kinderszenen 05",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Figures in translucent dresses leap hand in hand across a deep blue terrace",
    image: "/works/kinderszenen-05.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-06",
    title: "Kinderszenen 06",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A figure floats sideways inside a transparent green box threaded with long leaves",
    image: "/works/kinderszenen-06.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "kinderszenen-07",
    title: "Kinderszenen 07",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A solitary musician plays a white grand piano above reflective dark water and foliage",
    image: "/works/kinderszenen-07.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "kinderszenen-08",
    title: "Kinderszenen 08",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Three figures, blue flowers and looping vertebrae move among framed pale heads",
    image: "/works/kinderszenen-08.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "kinderszenen-09",
    title: "Kinderszenen 09",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A seated woman in a flowing white dress is crowned by a colorful stained-glass lampshade",
    image: "/works/kinderszenen-09.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-10",
    title: "Kinderszenen 10",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "An inverted face rests in a mass of dark feather-like foliage visited by yellow birds",
    image: "/works/kinderszenen-10.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "kinderszenen-11",
    title: "Kinderszenen 11",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A solitary figure climbs sunlit stone steps through a dense green forest",
    image: "/works/kinderszenen-11.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-12",
    title: "Kinderszenen 12",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A figure stands in reflective green water beside a luminous crescent and dark window frames",
    image: "/works/kinderszenen-12.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "kinderszenen-13",
    title: "Kinderszenen 13",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "Butterflies and flowers gather inside a transparent globe around a braided figure in white",
    image: "/works/kinderszenen-13.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "kinderszenen-14",
    title: "Kinderszenen 14",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A seated woman in white holds a toy rabbit beside an empty birdcage and scattered pages",
    image: "/works/kinderszenen-14.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "kinderszenen-15",
    title: "Kinderszenen 15",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A woman in a purple skirt dances above reflective blue water beneath an open sky",
    image: "/works/kinderszenen-15.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-16",
    title: "Kinderszenen 16",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A smiling cellist plays among a flock of white cranes in flight",
    image: "/works/kinderszenen-16.jpg",
    artClass: "geometry",
    featured: true,
  },
  {
    slug: "kinderszenen-17",
    title: "Kinderszenen 17",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A figure in white carries a red kite whose ribbons trail through a green garden",
    image: "/works/kinderszenen-17.jpg",
    artClass: "rain",
    featured: true,
  },
  {
    slug: "kinderszenen-18",
    title: "Kinderszenen 18",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A red-haired woman in a white dress and red shoes stands among luminous flowers",
    image: "/works/kinderszenen-18.jpg",
    artClass: "afternoon",
    featured: true,
  },
  {
    slug: "kinderszenen-19",
    title: "Kinderszenen 19",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A violinist leans close to a white horse amid deep blue garden leaves",
    image: "/works/kinderszenen-19.jpg",
    artClass: "night",
    featured: true,
  },
  {
    slug: "kinderszenen-20",
    title: "Kinderszenen 20",
    year: "2021",
    medium: "DIGITAL PAINTING",
    alt: "A long-haired woman reclines among red fabric, lilies and scissors beneath two red birds",
    image: "/works/kinderszenen-20.jpg",
    artClass: "geometry",
    featured: true,
  },
];

export const kinderszenenProject = {
  slug: "kinderszenen",
  title: "Kinderszenen",
  year: "2021",
  medium: "Digital painting",
  description:
    "A series of twenty digital paintings that moves through gardens, music rooms and dreamlike interiors as fragments of childhood memory. Figures drift between play, performance and quiet estrangement, while plants, instruments and architectural thresholds turn familiar scenes into unstable emotional spaces.",
  works: kinderszenenWorks,
} as const;

export const projects = [
  throughMyBloodProject,
  addictedRedProject,
  transientSpaceProject,
  stemProject,
  moonInTheWaterProject,
  untitledPencilProject,
  amusingOurselvesToDeathProject,
  kinderszenenProject,
] as const;
